# Prometheus 기본 설정
prometheus:
  prometheusSpec:
    retention: 10d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi  # 최소 용량 지정

# Grafana 설정
grafana:
  enabled: true
  adminUser: "admin"
  adminPassword: "admin"

  # NodePort 방식
  service:
    type: NodePort
    nodePort: 32000

  persistence:
    enabled: true
    size: 10Gi
    storageClassName: "local-path"

  # ✅ Provisioned DataSource 추가
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus          # 데이터 소스 이름
          type: prometheus
          access: proxy
          url: http://prometheus.monitoring:9090  # 실제 서비스 주소
          isDefault: true
          editable: true

  # Dashboard 제공
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: "K3s Cluster"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      k3s-cluster-19972:
        gnetId: 19972
        revision: 1
        datasource:
          - name: Prometheus  # 데이터 소스 이름과 동일하게 설정
            value: Prometheus

# node-exporter 설정
prometheus-node-exporter:
  hostRootFsMount:
    enabled: true

# kubelet cAdvisor 설정
kubelet:
  serviceMonitor:
    https: true
    insecureSkipVerify: true
    cAdvisor: true
    cAdvisorRelabelings:
      - action: replace
        sourceLabels: [__metrics_path__]
        targetLabel: metrics_path