prometheus:
  prometheusSpec:
    retention: 10d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

grafana:
  enabled: true
  adminUser: "admin"
  adminPassword: "admin"

  service:
    type: NodePort
    nodePort: 32000

  persistence:
    enabled: true
    size: 10Gi
    storageClassName: "local-path"

  # ✅ Provisioned DataSource 추가
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus          # DataSource 이름
          type: prometheus
          access: proxy
          url: http://prometheus.monitoring:9090  # ✅ 여기가 핵심
          isDefault: true
          editable: true

  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "default"
          orgId: 1
          folder: "K3s Cluster"
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default

  dashboards:
    default:
      k3s-cluster-19972:
        gnetId: 19972
        revision: 1
        datasource:
          - name: Prometheus      # Provisioned datasource 이름과 동일하게
            value: Prometheus

prometheus-node-exporter:
  hostRootFsMount:
    enabled: true

kubelet:
  serviceMonitor:
    https: true
    insecureSkipVerify: true
    cAdvisor: true
    cAdvisorRelabelings:
      - action: replace
        sourceLabels: [__metrics_path__]
        targetLabel: metrics_path