plugin: amazon.aws.aws_ec2

regions:
  - ap-northeast-2

filters:
  tag:Project: "k3s-project"
  instance-state-name: [ "running" ]

keyed_groups:
  - key: tags.Role
    separator: ""

hostnames:
  - private-ip-address

compose:
  ansible_user: ubuntu

  ansible_host: >-
    {{ public_ip_address if tag_Role == 'server'
       else private_ip_address }}

  ansible_ssh_common_args: >-
    {{ "-o ProxyCommand='ssh -W %h:%p -q ubuntu@" +
    hostvars[groups['server'][0]].public_ip_address +
    " -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa'"
    if tag_Role == 'agent' else "" }}