# 1. Helm 설치
- name: Install Helm via script
  ansible.builtin.shell: |
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh
  args:
    creates: /usr/local/bin/helm
  become: true

# 2. Helm repo 추가
- name: Add Prometheus community repo
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: "https://prometheus-community.github.io/helm-charts"
  become: true

# 3. monitoring 네임스페이스 생성
- name: Create monitoring namespace
  kubernetes.core.k8s:
    name: "{{ monitoring_namespace }}"
    kind: Namespace
    state: present
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
  become: true

# 4. kube-prometheus-stack 설치
- name: Deploy kube-prometheus-stack
  kubernetes.core.helm:
    name: "prometheus-stack"
    chart_ref: "prometheus-community/kube-prometheus-stack"
    chart_version: "{{ prometheus_chart_version }}"
    release_namespace: "{{ monitoring_namespace }}"
    kubeconfig: "/etc/rancher/k3s/k3s.yaml"
    binary_path: /usr/local/bin/helm
    values: "{{ lookup('file', role_path + '/files/custom-values.yaml') | from_yaml | combine(dynamic_values, recursive=True) }}"
    wait: true
    timeout: 900s  # ⬅️ 단위 붙임, Helm 요구 사항
  become: true
  vars:
    dynamic_values:
      grafana:
        service:
          type: NodePort
          nodePort: 32000
        grafana.ini:
          server:
            root_url: "http://{{ ansible_host }}:32000"